import Head from "next/head";
import Image from "next/image";
import {
  FaGithub,
  FaLinkedin,
  FaInstagram,
  FaFacebookSquare,
  FaDownload,
} from "react-icons/fa";
import Link from "next/link";
import { Tab } from "@headlessui/react";
import { getSortedPostsData } from "../utils/posts";
import BlogList from "../components/BlogList";
import Journey from "../components/Journey";
import About from "../components/About";

interface Home {
  allPostsData: Array<String>;
}

const Home = ({ allPostsData }: Home) => {
  return (
    <div className="bg-graywhite h-full">
      <Head>
        <title>Frisko Mayufid | Javascript Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto px-4 md:w-[600px]">
        <div className="flex items-center pt-6 justify-center">
          <Image
            src="/assets/profile.svg"
            alt="Picture of the author"
            width={100}
            height={100}
          />
          <div className="ml-4">
            <h1 className="text-3xl font-medium text-primary">
              Frisko Mayufid
            </h1>
            <h3 className="text-xl font-medium text-secondary">
              Javascript Developer
            </h3>
            <div className="flex mt-2 text-secondary">
              <Link href="https://github.com/friskomayufid">
                <a className="mr-4">
                  <FaGithub />
                </a>
              </Link>
              <Link href="https://www.linkedin.com/in/friskomayufid/">
                <a className="mr-4">
                  <FaLinkedin />
                </a>
              </Link>
              <Link href="https://www.instagram.com/myxxfd/">
                <a className="mr-4">
                  <FaInstagram />
                </a>
              </Link>
              <Link href="https://www.facebook.com/Friskomayufid/">
                <a className="mr-4">
                  <FaFacebookSquare />
                </a>
              </Link>
            </div>
          </div>
        </div>
        <div className="flex font-medium mt-6">
          <div className="flex-1 text-center text-secondary">
            <p>4</p>
            <p className="leading-5">Years of work experience</p>
          </div>
          <div className="flex-1 text-center text-secondary">
            <p>15+</p>
            <p className="leading-5">Completed projects</p>
          </div>
          <div className="flex-1 text-center text-secondary">
            <p>4</p>
            <p className="leading-5">Different Companies</p>
          </div>
        </div>
        <div className="flex space-x-2 mt-10">
          <button className="flex-1 text-white text-center bg-mainred border-mainred py-3 px-4 flex rounded-md justify-center">
            <a
              target="_blank"
              href="https://drive.google.com/file/d/15Aqlhwm_5eDcArkRztPIZj-104MJs-yd/view?usp=sharing"
              className="flex"
              rel="noopener noreferrer"
            >
              Download CV
              <div className="ml-2 mt-1">
                <FaDownload />
              </div>
            </a>
          </button>
          <button className="flex-1 text-primary text-center bg-white font-medium border-white py-3 px-4 flex rounded-md justify-center">
            <Link href="https://wa.me/6285329107849?text=Hi%20Frisko!%20">
              <a>Contact me</a>
            </Link>
          </button>
        </div>
        <section className="mt-8">
          <About />
        </section>
        <section className="mt-8">
          <Journey />
        </section>
        <section className="mt-8">
          <BlogList list={allPostsData} />
        </section>
      </div>
    </div>
  );
};

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

export default Home;
